// متابعة المشاركة — إعداد الأستاذ خليل البلوشي
// استبدل الكود في مشروع Google الحالي. يحافظ على SHEET_ID وAPI_KEY والبيانات السابقة.
const ROSTER = {"1":true,"2":true,"3":true};
function emptyState(){return {version:0,records:[],seen:[]};}
function cycleDetails(state){const details=Array.from({length:5},()=>({slots:Array(10).fill(null),manualComplete:false,result:null}));for(const r of state.records){if(r.cycleEdits?.length){for(const edit of r.cycleEdits)details[edit.index]={slots:edit.slots.slice(),manualComplete:edit.manualComplete,result:edit.result};}else if(r.participation!==null&&r.participation!==undefined){const c=details.find(c=>!c.manualComplete&&c.slots.includes(null));if(c)c.slots[c.slots.indexOf(null)]=r.participation;}}return details.map(c=>({...c,count:c.slots.filter(v=>v!==null).length,complete:c.manualComplete||c.slots.every(v=>v!==null),score:c.manualComplete?c.result:c.slots.every(v=>v!==null)?c.slots.reduce((n,v)=>n+v,0):null}));}
function progress(state){const details=cycleDetails(state),cycles=details.filter(c=>c.complete).map(c=>c.score),first=details.find(c=>!c.complete);return {cycles,details,resultByCycle:details.map(c=>c.score),current:first?.count||0,total:details.reduce((n,c)=>n+(c.manualComplete?10:c.count),0),entries:state.records.filter(r=>r.participation!==null&&r.participation!==undefined)};}
function validateCycleEdits(edits){if(!Array.isArray(edits)||edits.length>5)throw Error('تعديل الدورات غير صحيح');const seen=new Set();for(const e of edits){if(!Number.isInteger(e.index)||e.index<0||e.index>4||seen.has(e.index))throw Error('رقم الدورة غير صحيح');seen.add(e.index);if(!Array.isArray(e.slots)||e.slots.length!==10||e.slots.some(v=>v!==null&&![0,0.5,1].includes(v)))throw Error('خانات المشاركة غير صحيحة');if(typeof e.manualComplete!=='boolean')throw Error('حالة اكتمال الدورة غير صحيحة');if(e.manualComplete&&(typeof e.result!=='number'||!Number.isFinite(e.result)||e.result<0||e.result>10))throw Error('أدخل نتيجة الدورة المكتملة من ٠ إلى ١٠');if(!e.manualComplete&&e.result!==null)throw Error('نتيجة الدورة غير صحيحة');}}
function isParticipationRecord(r){return !!r.cycleEdits?.length||(r.participation!==null&&r.participation!==undefined);}
function changedCycleEdits(state,edits){validateCycleEdits(edits);const current=progress(state).details;return edits.filter(e=>{const c=current[e.index];return e.manualComplete!==c.manualComplete||e.result!==c.result||e.slots.some((v,i)=>v!==c.slots[i]);});}
function applyRecord(state,event){if(state.seen.includes(event.requestId))return state;let edits;if(event.action!=='undo'&&event.record.cycleEdits!==undefined){edits=changedCycleEdits(state,event.record.cycleEdits);if(!edits.length)return state;}if(event.version!==state.version)throw Error('تغيرت بيانات الطالب. حدّث الصفحة ثم راجع الرصد وأعد الحفظ.');const next=JSON.parse(JSON.stringify(state));if(event.action==='undo'){let index=-1;for(let i=next.records.length-1;i>=0;i--)if(isParticipationRecord(next.records[i])){index=i;break;}if(index<0)throw Error('لا توجد مشاركة للتراجع عنها');next.records.splice(index,1);}else{const p=event.record.participation;if(p!==null&&![0,0.5,1].includes(p))throw Error('نتيجة المشاركة غير صحيحة');if(p!==null&&progress(next).total>=50)throw Error('اكتملت دورات المشاركة الخمس');next.records.push({...event.record,...(edits?{cycleEdits:edits}:{}),id:event.requestId});}next.seen.push(event.requestId);next.version++;return next;}
if(typeof module!=='undefined')module.exports={emptyState,progress,applyRecord,cycleDetails,validateCycleEdits,isParticipationRecord,changedCycleEdits};

function setup_(){migrationCheck_();enableSync_();}
function doGet(e){if(e&&e.parameter.bridge==='1'){const nonce=String(e.parameter.nonce||''),origin=String(e.parameter.origin||'');if(!/^[a-zA-Z0-9-]{20,80}$/.test(nonce)||origin!=='https://omk811.github.io')return HtmlService.createHtmlOutput('رابط اتصال غير معتمد');const html="<!doctype html><html><head><meta charset=\"UTF-8\"><meta name=\"referrer\" content=\"no-referrer\"></head><body><script>\nconst nonce=__NONCE__,hostOrigin=__ORIGIN__;\nfunction send(data){window.top.postMessage({channel:'participation-bridge',nonce,...data},hostOrigin);}\nwindow.addEventListener('message',event=>{const m=event.data;if(event.source!==window.top||event.origin!==hostOrigin||!m||m.channel!=='participation-bridge'||m.nonce!==nonce||m.kind!=='request'||typeof m.id!=='string')return;google.script.run.withSuccessHandler(result=>send({kind:'response',id:m.id,result})).withFailureHandler(error=>send({kind:'response',id:m.id,error:error.message||'تعذر الاتصال بجدول Google'})).callParticipation(m.payload);});\nsend({kind:'ready'});\n</script></body></html>\n".replace('__NONCE__',JSON.stringify(nonce)).replace('__ORIGIN__',JSON.stringify(origin));return HtmlService.createHtmlOutput(html).setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}return json_({ok:true,app:'participation',version:'2026-10-05',capabilities:['participation-cycles','certificates','sheets-sync','github-bridge']});}
function callParticipation(payload){if(!payload||!['read','save','undo'].includes(payload.action))return {ok:false,error:'عملية غير معروفة'};const props=PropertiesService.getScriptProperties();if(payload.key!==props.getProperty('API_KEY')||!props.getProperty('API_KEY'))return {ok:false,error:'مفتاح الربط غير صحيح'};const ss=SpreadsheetApp.openById(props.getProperty('SHEET_ID'));if(!ss.getSheetByName('المشاركة'))enableSync_();return JSON.parse(doPost({postData:{contents:JSON.stringify(payload)}}).getContent());}
function migrationCheck_(){const props=PropertiesService.getScriptProperties();if(!props.getProperty('SHEET_ID')||!props.getProperty('API_KEY'))throw Error('استخدم مشروع Apps Script الحالي المرتبط بجدولك، ثم شغّل migrationCheck');const ss=SpreadsheetApp.openById(props.getProperty('SHEET_ID')),sheet=ss.getSheetByName('ملخص الطلبة');if(!sheet||sheet.getLastRow()<2)throw Error('لم يوجد ملخص الطلبة. لم يحدث أي تغيير في بياناتك');const rows=sheet.getRange(2,1,sheet.getLastRow()-1,sheet.getLastColumn()).getValues();rows.forEach(row=>{const state=JSON.parse(row.slice(13).join(''));if(!Array.isArray(state.records)||!Array.isArray(state.seen))throw Error('صيغة بيانات غير صالحة للطالب '+row[0]);});console.log('الجدول الحالي صالح للنقل. عدد الطلبة: '+rows.length);console.log('رابط الجدول: '+ss.getUrl());}
function json_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);}
function doPost(e){
 let lock;
 try{
 const q=JSON.parse(e.postData.contents),props=PropertiesService.getScriptProperties();
 if(!props.getProperty('API_KEY')||q.key!==props.getProperty('API_KEY'))throw Error('مفتاح الربط غير صحيح');
 const ss=SpreadsheetApp.openById(props.getProperty('SHEET_ID')),sheet=ss.getSheetByName('ملخص الطلبة');
 lock=LockService.getScriptLock();lock.waitLock(25000);
 const context=syncContext_(ss),rows=sheet.getRange(2,1,sheet.getLastRow()-1,sheet.getLastColumn()).getValues();
 if(q.action==='read'){if(!ROSTER[q.classId])throw Error('شعبة غير صحيحة');const states={},students=[];rows.forEach((r,index)=>{if(String(r[0]).split('-')[0]===q.classId){states[r[0]]=syncStudent_(context,sheet,index,r,JSON.parse(r.slice(13).join('')));students.push({id:r[0],name:String(r[2])});}});return json_({ok:true,states,students,sheetUrl:ss.getUrl(),protocol:4,capabilities:["participation-cycles","sheets-sync"],backendVersion:"2026-10-05"});}
 if(!['save','undo'].includes(q.action))throw Error('عملية غير معروفة');
 if(typeof q.requestId!=='string'||!/^[-a-zA-Z0-9]{20,80}$/.test(q.requestId))throw Error('معرف عملية غير صحيح');
 const idx=rows.findIndex(r=>r[0]===q.studentId);if(idx<0)throw Error('الطالب غير موجود');
 const row=rows[idx],old=syncStudent_(context,sheet,idx,row,JSON.parse(row.slice(13).join('')));
 if(old.seen.includes(q.requestId)||old.records.some(r=>r.id===q.requestId))return json_({ok:true,state:old,duplicate:true});
 if(q.action==='save')validate_(q.record);
 const state=applyRecord(old,q),now=new Date().toISOString();if(state===old)return json_({ok:true,state:old,noChange:true});
 // جداول التحرير أولًا؛ يمكن إعادة استيرادها عند تعثر حفظ النسخة الداخلية.
 assertSheetSnapshot_(context,q.studentId);publishStudent_(context,row,state);saveState_(sheet,idx,row,state);SpreadsheetApp.flush();
 let auditWarning=false;
 try{let log=ss.getSheetByName('سجل المشاركة');if(!log){log=ss.insertSheet('سجل المشاركة');log.getRange('D:D').setNumberFormat('@');log.appendRow(['معرف العملية','وقت الحفظ','الإجراء','معرف الطالب','الشعبة','اسم الطالب','تاريخ المشاركة','تفاصيل الدورات']);}const r=q.action==='save'?q.record:[...old.records].reverse().find(isParticipationRecord);log.appendRow([q.requestId,now,q.action==='save'?'تعديل المشاركة':'تراجع',row[0],row[1],row[2],r?.date||'',r?.cycleEdits?.map(c=>'الدورة '+(c.index+1)+': '+(c.manualComplete?'مكتملة من الورقي؛ النتيجة '+c.result:c.slots.filter(v=>v!==null).length+'/10')).join(' | ')||'مشاركة قديمة']);}catch(err){auditWarning=true;}
 return json_({ok:true,state:state,auditWarning:auditWarning});
 }catch(err){return json_({ok:false,error:err.message||'تعذر الحفظ'});}finally{if(lock&&lock.hasLock())lock.releaseLock();}
}
function validate_(r){
 if(!r||!/^\d{4}-\d{2}-\d{2}$/.test(r.date)||isNaN(Date.parse(r.date)))throw Error('تاريخ غير صحيح');
 if(r.participation!==null)throw Error('استخدم خانات الدورات لتسجيل المشاركة');
 validateCycleEdits(r.cycleEdits);if(!r.cycleEdits.length)throw Error('لا توجد خانات مشاركة معدلة');
 if(r.homework||r.behavior?.length||r.reading?.length||r.notes?.length||r.text)throw Error('هذا النظام مخصص للمشاركة فقط');
}

// جداول التحرير تُقرأ قبل كل قراءة وحفظ، وتُعاد كتابتها بعد الحفظ.
const CYCLE_HEADERS=['معرف الطالب','اسم الطالب','الشعبة','الدورة','مكتملة من الورقي','النتيجة من 10',...Array.from({length:10},(_,i)=>'مشاركة '+(i+1))];
function syncPlain_(value){return value===null||value===undefined?'':String(value).trim();}
function syncBool_(v){if(v===true||v==='TRUE'||v===1||v==='1')return true;if(v===false||v===''||v===null||v==='FALSE'||v===0||v==='0')return false;throw Error('استخدم مربع الاختيار للحالة');}
function syncScore_(v){if(v===''||v===null)return null;const n=Number(v);if(!Number.isFinite(n)||n<0||n>10)throw Error('نتيجة الدورة يجب أن تكون بين 0 و10');return n;}
function cycleSnapshot_(c){return {slots:c.slots.slice(),manualComplete:c.manualComplete,result:c.result};}
function cycleRow_(id,name,className,i,c){return [id,name,className,i+1,c.manualComplete,c.score===null?'':c.score,...c.slots.map(v=>v===null?'':v)];}
function reconcileStudent_(row,state,cycleRows,dailyRows,date,makeId){
 const before=progress(state),next=JSON.parse(JSON.stringify(state)),id=syncPlain_(row[0]);let changed=false;const cycleEdits=[];
 for(let i=0;i<5;i++){
  const base=cycleSnapshot_(before.details[i]),item=cycleRows.find(r=>syncPlain_(r.values[0])===id&&Number(r.values[3])===i+1);if(!item)throw Error('صف الدورة '+(i+1)+' مفقود للطالب '+row[2]+'؛ أعد تشغيل enableSync لإصلاح الخانات');
  const cells=item.values;const slots=cells.slice(6,16).map(v=>{if(v==='')return null;const n=Number(v);if(![0,0.5,1].includes(n))throw Error('مشاركة غير صحيحة للطالب '+row[2]+' في الدورة '+(i+1));return n;});
  let manual=syncBool_(cells[4]),score=syncScore_(cells[5]);
  if(score!==before.details[i].score&&score!==null)manual=true;
  const candidate={slots,manualComplete:manual,result:manual?score:null};
  const tableDirty=JSON.stringify(candidate)!==JSON.stringify(base),summaryScore=syncScore_(row[5+i]),summaryDirty=summaryScore!==before.resultByCycle[i];
  let proposed=tableDirty?candidate:null;
  if(summaryDirty){const fromSummary={slots:(proposed||base).slots.slice(),manualComplete:summaryScore!==null,result:summaryScore};if(tableDirty){const tableResult=candidate.manualComplete?candidate.result:candidate.slots.every(v=>v!==null)?candidate.slots.reduce((n,v)=>n+v,0):null;if(tableResult!==summaryScore)throw Error('تعارض نتيجتين للطالب '+row[2]+' في الدورة '+(i+1)+' بين الملخص والمشاركة. وحّد النتيجة ثم حدّث الموقع.');}proposed=fromSummary;}
  if(proposed){validateCycleEdits([{...proposed,index:i}]);cycleEdits.push({...proposed,index:i});}
 }
 if(cycleEdits.length){next.records.push({id:makeId(),date,participation:null,cycleEdits,origin:'sheets'});changed=true;}
 if(changed)next.version++;
 return {state:next,changed};
}
function readTable_(sheet,width){return sheet.getLastRow()<2?[]:sheet.getRange(2,1,sheet.getLastRow()-1,width).getValues().map((values,index)=>({values,index:index+2}));}
function syncContext_(ss){const cycles=ss.getSheetByName('المشاركة');if(!cycles)throw Error('شغّل enableSync مرة واحدة لتجهيز خانات المشاركة');const cycleRows=readTable_(cycles,16),seen=new Set();for(const row of cycleRows){if(!syncPlain_(row.values[0]))continue;const key=syncPlain_(row.values[0])+':'+row.values[3];if(seen.has(key))throw Error('صف دورة مكرر في ورقة المشاركة: '+key);seen.add(key);}return {cycles,cycleRows};}
function saveState_(sheet,index,row,state){const p=progress(state),encoded=JSON.stringify(state),chunks=[];for(let i=0;i<encoded.length;i+=40000)chunks.push(encoded.slice(i,i+40000));const output=[row[0],row[1],row[2],p.cycles.length,p.current,...p.resultByCycle.map(v=>v===null?'':v),state.records.filter(isParticipationRecord).length,new Date().toISOString(),state.version,...chunks];while(output.length<row.length)output.push('');if(output.length>sheet.getMaxColumns())sheet.insertColumnsAfter(sheet.getMaxColumns(),output.length-sheet.getMaxColumns());sheet.getRange(index+2,1).setNumberFormat('@');sheet.getRange(index+2,1,1,output.length).setValues([output]);sheet.hideColumns(14,output.length-13);return output;}
function publishStudent_(context,row,state){const id=syncPlain_(row[0]),p=progress(state);for(let i=0;i<5;i++){const item=context.cycleRows.find(r=>syncPlain_(r.values[0])===id&&Number(r.values[3])===i+1);if(!item)throw Error('صف دورة مفقود');const values=cycleRow_(id,row[2],row[1],i,p.details[i]);context.cycles.getRange(item.index,1,1,16).setValues([values]);item.values=values;}
}
function assertSheetSnapshot_(context,id){const old=context.cycleRows.filter(r=>syncPlain_(r.values[0])===id),fresh=readTable_(context.cycles,16).filter(r=>syncPlain_(r.values[0])===id);if(JSON.stringify(old)!==JSON.stringify(fresh))throw Error('تغيرت بيانات الجدول أثناء المزامنة. أعد التحديث ثم راجع المشاركات.');}
function syncStudent_(context,summary,index,row,state){const r=reconcileStudent_(row,state,context.cycleRows,[],Utilities.formatDate(new Date(),'Asia/Muscat','yyyy-MM-dd'),()=>Utilities.getUuid());if(r.changed){assertSheetSnapshot_(context,syncPlain_(row[0]));publishStudent_(context,row,r.state);const saved=saveState_(summary,index,row,r.state);row.splice(0,row.length,...saved);}else if(context.cycleRows.some(x=>syncPlain_(x.values[0])===syncPlain_(row[0])&&x.values[1]!==row[2])){assertSheetSnapshot_(context,syncPlain_(row[0]));publishStudent_(context,row,state);}const p=progress(r.state);if(Number(row[3])!==p.cycles.length||Number(row[4])!==p.current||Number(row[10])!==r.state.records.filter(isParticipationRecord).length){const saved=saveState_(summary,index,row,r.state);row.splice(0,row.length,...saved);}return r.state;}
function enableSync_(){const props=PropertiesService.getScriptProperties();if(!props.getProperty('SHEET_ID'))throw Error('شغّل setup أولًا');const lock=LockService.getScriptLock();lock.waitLock(25000);try{const ss=SpreadsheetApp.openById(props.getProperty('SHEET_ID')),summary=ss.getSheetByName('ملخص الطلبة'),rows=summary.getRange(2,1,summary.getLastRow()-1,summary.getLastColumn()).getValues();let cycles=ss.getSheetByName('المشاركة');
 if(!cycles){cycles=ss.insertSheet('المشاركة');cycles.appendRow(CYCLE_HEADERS);const data=[];rows.forEach(row=>progress(JSON.parse(row.slice(13).join(''))).details.forEach((c,i)=>data.push(cycleRow_(syncPlain_(row[0]),row[2],row[1],i,c))));cycles.getRange(2,1,data.length,1).setNumberFormat('@');cycles.getRange(2,5,data.length,1).insertCheckboxes();cycles.getRange(2,1,data.length,16).setValues(data);}
 cycles.setRightToLeft(true);cycles.setFrozenRows(1);cycles.getRange(1,1,1,16).setBackground('#0c665c').setFontColor('#ffffff').setFontWeight('bold');cycles.setColumnWidth(2,310);cycles.getDataRange().setWrap(true);
 cycles.getRange('A:A').setNumberFormat('@');cycles.getRange('E1').setNote('يمكن تحديد اكتمال الدورة الورقية أو إلغاؤه. أدخل نتيجتها في العمود F.');cycles.getRange('G1:P1').setNote('فارغ = لم يرصد. 1 = مشاركة. 0.5 و0 محفوظتان للتقييمات السابقة ويمكن استعمالهما.');summary.getRange('D1:E1').setNote('محسوب تلقائيًا. عدّل الدورة والخانات في ورقة المشاركة.');summary.getRange('F1:J1').setNote('قابل للتحرير: إدخال درجة ينقلها كدورة مكتملة من الورقي. إفراغ الدرجة يلغي الاكتمال اليدوي مع الاحتفاظ بخانات المشاركة.');summary.getRange('K1').setValue('عدد تعديلات المشاركة');
 const existingRows=readTable_(cycles,16);for(const row of rows){const detail=progress(JSON.parse(row.slice(13).join(''))).details;for(let i=0;i<5;i++)if(!existingRows.some(x=>syncPlain_(x.values[0])===syncPlain_(row[0])&&Number(x.values[3])===i+1)){const values=cycleRow_(syncPlain_(row[0]),row[2],row[1],i,detail[i]);cycles.appendRow(values);existingRows.push({index:cycles.getLastRow(),values});}}
 const context=syncContext_(ss);rows.forEach((row,index)=>syncStudent_(context,summary,index,row,JSON.parse(row.slice(13).join(''))));props.setProperty('SYNC_ENABLED','4');SpreadsheetApp.flush();console.log('تم تفعيل المزامنة في الجدول الحالي: '+ss.getUrl());
 }finally{lock.releaseLock();}}
